### ISSUE TITLE
Title not propagating

### ISSUE THREAD

**Issue by muzuzu** [ibi/wf-extensions-chart#1]
In a number of the plug-ins (e.g. Sankey chart) if the title is changed from within InfoAssist this is not propagated to the end product. Rather it always continues to read "Drop Measures or Sorts Into The Query Pane." This looks to be because something missing in the renderCallback function but I can't seem to nail this down. Any ideas?

**Comment by remi-ibi** [comment]
Custom titles are only visible after the extension has enough data to draw successfully.  This is true for extensions as well as standard IA charts; custom titles are not visible on bar charts or pie charts that do not include any data.  The Sankey extension requires one field in each of its three buckets before it can draw, so we expect to see the 'Drop Measures or Sorts' title until all three buckets are filled.

However, once you add a field to each bucket, the title disappears entirely; this is a bug in the Sankey extension itself.

Extensions do not have to take any special action to draw the chart's title: titles are automatically drawn by the chart engine.  However, extensions are free to alter the chart's title before it is drawn via the extension's 'preRender' callback.  This is what the Sankey extension is using to draw the 'Drop Measures or Sorts' title.

The bug in Sankey is in com.ibi.sankey.js: line 16: 'preRenderCallback' is forcing the chart's title invisible if there is enough data.  This is wrong; in general, an extension with sufficient data should not alter the chart title (unless the extension has a strong reason to do so, of course).

I will fix this bug in the Sankey extension, and will verify that all other extensions work correctly with custom chart titles.  Thank you for reporting this!

**Comment by muzuzu** [comment]
Thanks for the quick turnaround, Remi! The customer will be thrilled.

Yash

________________________________

**Comment by remi-ibi** [comment]
I fixed the Sankey extension so it correctly draws the chart's title.
