### ISSUE TITLE
New Map?

### ISSUE THREAD

**Issue by RoofShingles** [ibi/wf-extensions-chart#41]
Hello,
What would I have to change to use a new map/image/image-map?  I have certain boundaries in my business that I would like to use as polygons in a map.  And of course, I'd like to color each of these polygons according to some calculated measure.  We do have these boundaries in GIS so we should be able to export them to several formats. 

Thank you,
Roofy

**Comment by phi0529** [comment]
Closing as there’s was no more feedback
