### ISSUE TITLE
Hiding a row only hides the values, not the header

### ISSUE THREAD

**Issue by TPhil10** [ibi/wf-extensions-chart#48]
When you NOPRINT a row (set visibility in the GUI to 'Hide'), the column disappears but not it's header.  All of the data shifts to the left one place but the column headers remain in place. 

~~~~
ENGINE INT CACHE SET ON
SET PAGE-NUM=NOLEAD
SET ARGRAPHENGINE=JSCHART
SET EMBEDHEADING=ON
SET GRAPHDEFAULT=OFF
-DEFAULTH &WF_STYLE_UNITS='PIXELS';
-DEFAULTH &WF_STYLE_HEIGHT='405.0';
-DEFAULTH &WF_STYLE_WIDTH='770.0';
-DEFAULTH &WF_TITLE='WebFOCUS Report';
GRAPH FILE car
-* Created by Info Assist for Graph
SUM CAR.BODY.RETAIL_COST
CAR.BODY.DEALER_COST
CAR.BODY.SALES
BY CAR.ORIGIN.COUNTRY NOPRINT
BY CAR.COMP.CAR
ON GRAPH PCHOLD FORMAT JSCHART
ON GRAPH SET VZERO OFF
ON GRAPH SET GRWIDTH 1
ON GRAPH SET AUTOFIT ON
ON GRAPH SET UNITS &WF_STYLE_UNITS
ON GRAPH SET HAXIS &WF_STYLE_WIDTH
ON GRAPH SET VAXIS &WF_STYLE_HEIGHT
ON GRAPH SET LOOKGRAPH EXTENSION
ON GRAPH SET AUTOFIT ON
ON GRAPH SET STYLE *
*GRAPH_SCRIPT
setPieDepth(0);
setPieTilt(0);
setDepthRadius(0); 
setPlace(true); 
setCurveFitEquationDisplay(false); 
*END
INCLUDE=IBFS:/FILE/IBI_HTML_DIR/ibi_themes/Warm.sty,$
TYPE=REPORT, TITLETEXT=&WF_TITLE.QUOTEDSTRING, $
TYPE=DATA, COLUMN=N1, BUCKET= >row, $
TYPE=DATA, COLUMN=N2, BUCKET= >row, $
TYPE=DATA, COLUMN=N3, BUCKET= >measure, $
TYPE=DATA, COLUMN=N4, BUCKET= >measure, $
TYPE=DATA, COLUMN=N5, BUCKET= >measure, $
*GRAPH_SCRIPT
setReportParsingErrors(false);
setSelectionEnableMove(false);
*GRAPH_JS_FINAL
"pieProperties": {
    "holeSize": "0%"
},
"chartType": "com.ibi.datatables",
"agnosticSettings": {
    "chartTypeFullName": "com.ibi.datatables"
}
*END
ENDSTYLE
END
-RUN
 
~~~~

**Comment by steebn** [comment]
Typical IBI (lack of) support

**Comment by phi0529** [comment]
For support please use http://techsupport.ibi.com extensions published here are maintained by different developers

**Comment by phi0529** [comment]
Closing as this is fixed already

**Comment by steebn** [comment]
Thank you for updating this. I apologize for the snarky comment before. It was a bit over the top.

I do think that you should know that from an end user's perspective, when you see issues that have been open for months on end, without insomuch as a comment on the issue, it **really** gives the appearance that you really don't care about your end user. (Just so you are aware, there are three other issues in the repo just like this).

If you need some insight on how to properly handle issues on github, there is some documentation that might help out https://guides.github.com/features/issues/

**Comment by phi0529** [comment]
Hi
Partially my fault.
I answered some of them in the past and forgot to close them. I’m not ibi support. just looking into this during a lazy day during my holidays.
From my experience it‘s always better to open a case within the Information Builders ticketing system if your request is urgent as this git repository is  managed by the developers of the extensions not by official Information Builders support.

**Comment by TPhil10** [comment]
Hi,
So if this has been fixed, was it fixed by IBI or fixed by the developer of the extension?  If the latter can you provide the commit ID so I can trace the fix.
On the topic of who maintains what, if you develop an extension for a product, that extension is likely not going to be supported by the product's owners.  If I go to the product's owner with that issue, they are going to tell me to go talk to the extensions owner as they do not maintain the extensions.  Also, maintaining code on a site like github which has extensive issue tracking features (among other things) and then saying if I find issues go to IBI's tech support site is incredibly counter-intuitive and inefficient.  If that's the case, why maintain the extension here at all.  

If the extension is not working the way it should with the product, it's the duty of the extension developer to fix it, not the product's owner.

Now having said all that, if it is fixed I'd like to thank the developer for their work on this extension.  The data tables lib is a very handy tool.
