### ISSUE TITLE
Sparktables error out and won't render on v8202M

### ISSUE THREAD

**Issue by steebn** [ibi/wf-extensions-chart#56]
When trying to run a fex using the sparktables extension, i get the following error (servername redacted):
```
Internal Error
TypeError: Cannot read property 'constructor' of undefined (details)
TypeError: Cannot read property 'constructor' of undefined at prep_data 
    (http://***********/ibi_apps/tdg/jschart/distribution/extensions/com.ibi.sparktables/com.ibi.sparktables.js:491:60) at Object.renderCallback 
    (http://***********/ibi_apps/tdg/jschart/distribution/extensions/com.ibi.sparktables/com.ibi.sparktables.js:63:20) at Object.drawExtensionInternal 
    (http://***********/ibi_apps/tdg/jschart/distribution/tdgchart-min.js:1564:337) at c 
    (http://***********/ibi_apps/tdg/jschart/distribution/tdgchart-min.js:393:313) at q 
    (http://***********/ibi_apps/tdg/jschart/distribution/tdgchart-min.js:396:516) at http://***********/ibi_apps/tdg/jschart/distribution/tdgchart-min.js:26:188 at Object.drawExtension 
    (http://***********/ibi_apps/tdg/jschart/distribution/tdgchart-min.js:1563:22) at http://***********/ibi_apps/tdg/jschart/distribution/tdgchart-min.js:1562:298 at Object.initCallback 
    (http://***********/ibi_apps/tdg/jschart/distribution/extensions/com.ibi.sparktables/com.ibi.sparktables.js:28:9) at Array.drawExtension 
    (http://***********/ibi_apps/tdg/jschart/distribution/tdgchart-min.js:1562:210)
```
The code for the fex is:
```
ENGINE INT CACHE SET ON
SET PAGE-NUM=NOLEAD
-DEFAULTH &WF_HTMLENCODE=OFF;
SET HTMLENCODE=&WF_HTMLENCODE

SET ARGRAPHENGINE=JSCHART
-DEFAULTH &WF_EMPTYREPORT=ON;
SET EMPTYREPORT=&WF_EMPTYREPORT

SET EMBEDHEADING=ON
SET GRAPHDEFAULT=OFF
-DEFAULTH &WF_STYLE_UNITS='PIXELS';
-DEFAULTH &WF_STYLE_HEIGHT='405.0';
-DEFAULTH &WF_STYLE_WIDTH='770.0';

-DEFAULTH &WF_TITLE='WebFOCUS Report';
GRAPH FILE ibisamp/ggsales
-* Created by Info Assist for Graph
SUM TOT.GGSALES.SALES01.DOLLARS
GGSALES.SALES01.DOLLARS
BY GGSALES.SALES01.CATEGORY
BY GGSALES.SALES01.PRODUCT
BY GGSALES.SALES01.DATE
ON GRAPH PCHOLD FORMAT JSCHART
ON GRAPH SET VZERO OFF
ON GRAPH SET UNITS &WF_STYLE_UNITS
ON GRAPH SET HAXIS &WF_STYLE_WIDTH
ON GRAPH SET VAXIS &WF_STYLE_HEIGHT
ON GRAPH SET LOOKGRAPH EXTENSION
ON GRAPH SET AUTOFIT ON
ON GRAPH SET STYLE *
*GRAPH_SCRIPT

setPieDepth(0);
setPieTilt(0);
setDepthRadius(0); 
setCurveFitEquationDisplay(false); 
setPlace(true); 

*END
INCLUDE=IBFS:/FILE/IBI_HTML_DIR/ibi_themes/endeflt.sty,$
TYPE=REPORT, TITLETEXT=&WF_TITLE.QUOTEDSTRING, $
TYPE=DATA, COLUMN=N1, BUCKET= >row, $
TYPE=DATA, COLUMN=N2, BUCKET= >row, $
TYPE=DATA, COLUMN=N3, BUCKET= >sparkline_date, $
TYPE=DATA, COLUMN=N4, BUCKET= >measure, $
TYPE=DATA, COLUMN=N5, BUCKET= >sparkline_value, $
*GRAPH_SCRIPT

setReportParsingErrors(false);
setSelectionEnableMove(false);
*GRAPH_JS_FINAL
"pieProperties": {
"holeSize": "0%"
},
"chartType": "com.ibi.sparktables",
"agnosticSettings": {
"chartTypeFullName": "com.ibi.sparktables"
}

*END
ENDSTYLE
END

-RUN

```

**Comment by IBIGraphGuy** [comment]
Your example worked for me. What version of WF are you running?

**Comment by phi0529** [comment]
Works perfect here as well - 

1. Please isntall the latest version of the extension (uninstall old release before reinstalling)
2. Clear WebFOCUS Cache (http://xxx/ibi_apps/admin - upper right corner "clear chache")
3. Clear your browser cache

This prolem is known but already fixed

**Comment by steebn** [comment]
I am on version 8202M.

1.  I just barely downloaded the extension today for the first time, so it is the most current version
2.  I've Cleared the cache in the admin console (multiple times) 
3.  I've Cleared browser cache (multiple times)

**Comment by steebn** [comment]
Sorry, closed it by mistake #noob

**Comment by phi0529** [comment]
ok I'm on 8206 - this extension might not be tested with 8202M as it's a relatively new extension

**Comment by steebn** [comment]
Interesting. The ReadMe file states that it is an:

> Extension for WebFocus 8200

**Comment by phi0529** [comment]
Just tested in 8202M - same problem.
Why so negative - Everyone here is trying to help? The extension is relatively new - done by a 3rd party developer and therefore maybe not tested with any release of WebFOCUS

**Comment by steebn** [comment]
I'm sorry, but what was so negative about that last comment? I was just stating that the ReadMe file states that it is an Extension for WebFOCUS 8200. I do really appreciate your help here. Thank you. It has been light years better than most of the "help" I've gotten from InfoResponseLive.

**Comment by phi0529** [comment]
The developer of the extension is looking into this - not promising anything as he is doing this during spare time.
The reason why 8202 is not automatically working is that with 8206 there was an extended API introduced that allows users to configure the extensions in WebFOCUS GUI - like change colors, ...
So newer extension depend on the developer to test and support both API releases. As most extensions are done outside IBI development team it‘s those developers that decide witch versions of the API they are going to support.
As you are using 8202 - take a look at 8206 - https://kb.informationbuilders.com/
Some great new features.

**Comment by IBIGraphGuy** [comment]
A new version of the extension has been uploaded that should work with 8202. Please check it out.

**Comment by steebn** [comment]
I updated the extension, and it is now working. Thank you so much
